// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrcJqR8sUWg3aTwpAVnmtr2BZ9HEOOFY',
    appId: '1:1038255999180:android:ffab2d6d57dc7509b31a69',
    messagingSenderId: '1038255999180',
    projectId: 'student-calendar-7246c',
    storageBucket: 'student-calendar-7246c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYQDGl1vp5vyzH5VmNqQHrufGRibDIyg',
    appId: '1:1038255999180:ios:dedc9d9d99078209b31a69',
    messagingSenderId: '1038255999180',
    projectId: 'student-calendar-7246c',
    storageBucket: 'student-calendar-7246c.appspot.com',
    iosClientId:
        '1038255999180-5ip5umkad236lm50iqfd9qrckg5slj4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.scApp',
  );
}
